# Generated by Django 5.2.8 on 2025-11-11 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название альбома')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL-метка')),
                ('content', models.TextField(verbose_name='Текст новости')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Обложка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Opponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название команды')),
                ('logo', models.ImageField(blank=True, upload_to='opponents/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Соперник',
                'verbose_name_plural': 'Соперники',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя и фамилия')),
                ('position', models.CharField(choices=[('libero', 'Либеро'), ('setter', 'Связующий'), ('outside', 'Доигровщик'), ('opposite', 'Диагональный'), ('middle', 'Центральный')], max_length=20, verbose_name='Позиция')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/', verbose_name='Фото')),
                ('bio', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.CreateModel(
            name='PlayerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('position', models.CharField(choices=[('libero', 'Либеро'), ('setter', 'Связующий'), ('outside', 'Доигровщик'), ('opposite', 'Диагональный'), ('middle', 'Центральный')], max_length=20, verbose_name='Позиция')),
                ('experience', models.TextField(blank=True, verbose_name='Опыт')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка на вступление',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: 2024/2025', max_length=100, verbose_name='Название сезона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Текущий сезон')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('content', models.TextField(max_length=1000, verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Одобрен')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='team.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('location', models.CharField(max_length=200, verbose_name='Место проведения')),
                ('is_home', models.BooleanField(default=True, verbose_name='Домашний матч')),
                ('sets_home', models.PositiveSmallIntegerField(default=0, verbose_name='Сеты (ИСКРА)')),
                ('sets_away', models.PositiveSmallIntegerField(default=0, verbose_name='Сеты (Соперник)')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.opponent', verbose_name='Соперник')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.season', verbose_name='Сезон')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='team.album', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LeagueStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, verbose_name='Название команды')),
                ('position', models.PositiveSmallIntegerField(verbose_name='Место')),
                ('played', models.PositiveSmallIntegerField(default=0, help_text='Игры', verbose_name='И')),
                ('wins', models.PositiveSmallIntegerField(default=0, verbose_name='В')),
                ('losses', models.PositiveSmallIntegerField(default=0, verbose_name='П')),
                ('sets_won', models.PositiveSmallIntegerField(default=0, verbose_name='Сеты+')),
                ('sets_lost', models.PositiveSmallIntegerField(default=0, verbose_name='Сеты-')),
                ('points', models.PositiveSmallIntegerField(default=0, verbose_name='Очки')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.season', verbose_name='Сезон')),
            ],
            options={
                'verbose_name': 'Позиция в таблице',
                'verbose_name_plural': 'Турнирная таблица',
                'ordering': ['season', 'position'],
            },
        ),
        migrations.CreateModel(
            name='PlayerMatchStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveSmallIntegerField(default=0, verbose_name='Очки')),
                ('aces', models.PositiveSmallIntegerField(default=0, verbose_name='Эйсы')),
                ('blocks', models.PositiveSmallIntegerField(default=0, verbose_name='Блоки')),
                ('receptions', models.PositiveSmallIntegerField(default=0, verbose_name='Приёмы')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.match', verbose_name='Матч')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Статистика игрока за матч',
                'verbose_name_plural': 'Статистика игроков',
                'unique_together': {('player', 'match')},
            },
        ),
    ]
